### ISSUE TITLE
data elements not exist

### ISSUE THREAD

**Issue by wallian** [yoshida-lab/XenonPy#135]
I installed development mode with this site,
https://xenonpy.readthedocs.io/en/latest/installation.html

and tried to check the preset.elements with this page.
https://xenonpy.readthedocs.io/en/latest/tutorial/1-dataset.html

then I got the following  error message.
```
>>> preset.elements
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hagawa/codes/xenonpy/XenonPy/xenonpy/datatools/preset.py", line 230, in elements
    self._check('elements')
  File "/home/hagawa/codes/xenonpy/XenonPy/xenonpy/datatools/preset.py", line 192, in _check
    "data {0} not exist, please run <Preset.sync('{0}')> to download from the repository".format(data))
RuntimeError: data elements not exist, please run <Preset.sync('elements')> to download from the repository
```

I cannot calculate descriptor without this preset.elements data.
How can I get it?

```
>>> from xenonpy.datatools import preset
```
doesn't make any error.
I'm using Ubuntu18.04 and Anaconda.

**Comment by wallian** [comment]
OK, I solved this problem with following  line:
```
>>> preset.sync("elements")
```

If it is important, you would better write this on installation page.

**Comment by TsumiNa** [comment]
Hi @wallian. Thanks for your feedback. Instead of written everything on the docs, we decided to raise some `RuntimeError` to let users know what happened and how to address it because xenonpy has too many parts.

But yes, as you said, our docs are still insufficient. We have scheduled the docs updating. We hope this can be done this year.
